In [1]:
import my_linear_algebra as mla

In [27]:
A = [[1,2],[3,4]]

In [28]:
mla.deepcopy(A)

[[1, 2], [3, 4]]

# 벡터의 사칙연산

In [29]:
# 벡터의 덛셈
u = [1,2,3]
v = [4,5,6]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] + v[i]
    w.append(val)

print(w)
# 함수로 저장
print(mla.v_add(u, v))

[5, 7, 9]
[5, 7, 9]


In [2]:
u = [7, 3, 9]
v = [2, 5, 7]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] - v[i]
    w.append(val)

print(w)
# 뺄셈 함수 구현
# print()
mla.v_subtract(u, v)

[5, -2, 2]


[5, -2, 2]

In [3]:
u = [2, 4, 3]
a = 3

n = len(u)
w = []

for i in range(0, n):
    val = a * u[i]
    w.append(val)

print(w)
mla.scalar_v_mul(a,u)

[6, 12, 9]


[6, 12, 9]

In [ ]:
u = [1, 2, 4]
v = [7, 3, 2]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] * v[i]
    w.append(val)

print(w)
print(mla.v_mul(u,v))
# 원소 나눗셈은 생략

# 넘파이 실습

In [14]:
import numpy as np

In [16]:
u = np.array([1,2,3])
v = np.array([4,5,6])
w = u+v
print(w)

[5 7 9]


In [19]:
u = np.array([7,3,9])
v = np.array([2,5,7])
w= u-v
print(w)

[ 5 -2  2]


In [20]:
a = 3
u = np.array([1,2,4])
w = a * u
print(w)

[ 3  6 12]


In [21]:
u = np.array([1,2,4])
v = np.array([7,3,2])
w = u*v
print(w)

[7 6 8]


In [22]:
u = np.array([6,5,9])
v = np.array([2,2,-3])
w = u/v
print(w)

[ 3.   2.5 -3. ]


In [2]:
A = [[2,7],[3,4],[6,1]]
B = [[1,4],[4,-1],[2,5]]

n = len(A)
p = len(A[0])

res =[]

for i in range(0,n):
    row=[]
    for j in range(0,p):
        val = A[i][j] + B[i][j]
        row.append(val)
    res.append(row)

print(res)

[[3, 11], [7, 3], [8, 6]]


In [16]:
import numpy as np

In [18]:
#행렬 스칼라 곱
A = np.array([[2,7], [3,4], [6,1]])
b = 2
C = A*b
print(C)

[[ 4 14]
 [ 6  8]
 [12  2]]


In [20]:
#행렬의 원소 곱
A = np.array([[1, 5], [6, 4], [2, 7]])
B = np.array([[5, -1], [1, 2], [4, 1]])
C = np.multiply(A, B)
print(C)

[[ 5 -5]
 [ 6  8]
 [ 8  7]]


In [21]:
#그냥해도 되는데?
A*B

array([[ 5, -5],
       [ 6,  8],
       [ 8,  7]])

In [22]:
A = np.array([[2, 7], [3, 4], [5, 2]])
B = np.array([[3, -3, 5], [-1, 2, -1]])
C =np.matmul(A, B)
print(C)

[[ -1   8   3]
 [  5  -1  11]
 [ 13 -11  23]]


In [4]:
A= [[1,5],[3,4],[6,2]]
n=len(A)
p=len(A[0])
C=[]
for i in range(0, p):
    row=[]
    for j in range(0, n):
        val = A[j][i]
        row.append(val)
    C.append(row)
print(C)

[[1, 3, 6], [5, 4, 2]]


In [2]:
import numpy as np

In [7]:
A=np.array([[1,5],[3,4],[6,2]])
# At= A.T
At = np.transpose(A)
print(At)

[[1 3 6]
 [5 4 2]]


In [8]:
A = [[1,0,2],
    [0,2,1],
    [2,1,1]]

In [9]:
At = mla.transpose(A)
print(At)

[[1, 0, 2], [0, 2, 1], [2, 1, 1]]


In [10]:
A==At

True

In [11]:
AA = A
for i in range(0, 9):
    AA = mla.matmul(AA, A)
    print('행렬 A의', i+2, "제곱은", AA)

행렬 A의 2 제곱은 [[5, 2, 4], [2, 5, 3], [4, 3, 6]]
행렬 A의 3 제곱은 [[13, 8, 16], [8, 13, 12], [16, 12, 17]]
행렬 A의 4 제곱은 [[45, 32, 50], [32, 38, 41], [50, 41, 61]]
행렬 A의 5 제곱은 [[145, 114, 172], [114, 117, 143], [172, 143, 202]]
행렬 A의 6 제곱은 [[489, 400, 576], [400, 377, 488], [576, 488, 689]]
행렬 A의 7 제곱은 [[1641, 1376, 1954], [1376, 1242, 1665], [1954, 1665, 2329]]
행렬 A의 8 제곱은 [[5549, 4706, 6612], [4706, 4149, 5659], [6612, 5659, 7902]]
행렬 A의 9 제곱은 [[18773, 16024, 22416], [16024, 13957, 19220], [22416, 19220, 26785]]
행렬 A의 10 제곱은 [[63605, 54464, 75986], [54464, 47134, 65225], [75986, 65225, 90837]]


In [12]:
print(A)
print(At)

[[1, 0, 2], [0, 2, 1], [2, 1, 1]]
[[1, 0, 2], [0, 2, 1], [2, 1, 1]]


In [16]:
A=[[1,0,3],[2,1,4],[0,1,1]]
At = mla.transpose(A)
print(A)
print(At)

[[1, 0, 3], [2, 1, 4], [0, 1, 1]]
[[1, 2, 0], [0, 1, 1], [3, 4, 1]]


In [4]:
# A의 대각행렬구하기 
A=[[1,2,3],[4,5,6],[7,8,9]]
n = len(A)
p = len(A[0])

D=[]
for i in range(n):
    pwd=[]
    for j in range(p):
        if i==j:
            pwd.append(A[i][j])
        else:
            pwd.append(0)
    D.append(pwd)
print(D)

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]


In [ ]:
#대각행렬 이후 작업 필요
